// <auto-generated />
using System;
using CRUDApi2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDAPI2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240116152450_Corrected migration")]
    partial class Correctedmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CRUDApi2.AreaDeConhecimento", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AreaNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AreaId");

                    b.ToTable("AreasDeConhecimento");
                });

            modelBuilder.Entity("CRUDApi2.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("CRUDApi2.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LivroNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LivroId");

                    b.HasIndex("AreaId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("CRUDApi2.LivroAutor", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("LivroId1")
                        .HasColumnType("int");

                    b.HasKey("LivroId");

                    b.HasIndex("AutorId");

                    b.HasIndex("LivroId1");

                    b.ToTable("LivroAutores");
                });

            modelBuilder.Entity("CRUDApi2.Livro", b =>
                {
                    b.HasOne("CRUDApi2.AreaDeConhecimento", "AreaDeConhecimento")
                        .WithMany("Livros")
                        .HasForeignKey("AreaId");

                    b.Navigation("AreaDeConhecimento");
                });

            modelBuilder.Entity("CRUDApi2.LivroAutor", b =>
                {
                    b.HasOne("CRUDApi2.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDApi2.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("CRUDApi2.AreaDeConhecimento", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
