// <auto-generated />
using System;
using CRUDApi2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDAPI2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CRUDApi2.AreaDeConhecimento", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AreaNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AreaId");

                    b.ToTable("AreasDeConhecimento");
                });

            modelBuilder.Entity("CRUDApi2.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("CRUDApi2.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("AreaNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LivroNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LivroId");

                    b.HasIndex("AreaId");

                    b.HasIndex("AutorId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("CRUDApi2.Livro", b =>
                {
                    b.HasOne("CRUDApi2.AreaDeConhecimento", "AreaDeConhecimento")
                        .WithMany("Livros")
                        .HasForeignKey("AreaId");

                    b.HasOne("CRUDApi2.Autor", null)
                        .WithMany("Livros")
                        .HasForeignKey("AutorId");

                    b.Navigation("AreaDeConhecimento");
                });

            modelBuilder.Entity("CRUDApi2.AreaDeConhecimento", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("CRUDApi2.Autor", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
